server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true

spring:
  mvc:
    log-resolved-exception: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

app:
  jwt:
    key: (secret-key)
  oauth:
    callback: http://localhost:8080/oauth2/callback
